### PR TITLE
Fix REST route registration

### LINKED ISSUE #64: REST route registration error
On my local SAFMC site with debug log enabled:

PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>content-aggregator-block/v1/posts</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in /Users/elaine/Sites/safmc/wp-includes/functions.php on line 5768

### PR DESCRIPTION
**Pull request by webelaine**
- Add a newly-required parameter to the two calls to `register_rest_route()`: `permission_callback`.
- Both the Post and the Meta route are set to `__return_true`. At first I tried setting Meta to ensure the current user can `edit-posts`, but that was causing 500 errors in the Editor.

Fixes #64

### CODE REVIEW

File: includes/block.php [hunk 1]
```diff
@@ -474,25 +475,21 @@ function register_meta_endpoint() {
...
 
 /**
- * Return the meta keys registered for the provided post type.
- *
- * @param \WP_Request $request The incoming REST API request object.
- *
- * @return array Posts found using the provided parameters.
+ * Make sure only users who can edit posts can access this REST API route.
  */
-function meta_rest_response( $request ) {
```
Comment (philcable) [inline includes/block.php]: It looks like we should keep this function and remove `meta_rest_permission()` instead.

**Review by philcable — COMMENTED** [review]
Just one comment on what I think was a mix-up on the permissions callback removal.

File: includes/block.php (hunk 1 above)
Comment (webelaine) [reply includes/block.php]: Whoops! For sure.
